name: Update version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Increase version
      run: |
        VERSION=$(cat version.json | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' )

        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        PATCH=$(echo $VERSION | cut -d. -f3)

        PATCH=$((PATCH+1))

        NEW_VERSION="$MAJOR.$MINOR.$PATCH"

        echo "{\"version\":\"$NEW_VERSION\"}" > version.json


    - name: Commit version update
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add version.json
        git commit -m "Update version to $(cat version.json)" || exit 0
        git push