name: Update version

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:

  version:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Create version.json
      run: |

        VERSION=$(date +"%Y%m%d%H%M%S")

        echo "{
          \"version\": \"$VERSION\",
          \"date\": \"$(date)\"
        }" > version.json


    - name: Commit version
      run: |

        git config user.name "github-actions"

        git config user.email "github-actions@github.com"

        git add version.json

        git commit -m "Auto update version" || exit 0

        git push